"""
This script loads all the reports generated by the detection of critical lesions and analyzes them to identify the most common features of critical lesions.

Input:
    --report: path to the generated report (csv file)
    -o: path to the output folder where the analysis results will be saved.

Author: Pierre-Louis Benveniste
"""
import os
import argparse
import pandas as pd
from loguru import logger
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GroupKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from skopt import BayesSearchCV
from skopt.space import Integer, Real, Categorical
import prettytable
from scipy.stats import ttest_ind



def parse_args():
    parser = argparse.ArgumentParser(description="Analyze the reports generated by the detection of critical lesions to identify the most common features of critical lesions.")
    parser.add_argument("--report", type=str, required=True, help="Path to the generated report (csv file)")
    parser.add_argument("-o", "--output_folder", type=str, required=True, help="Path to the output folder where the analysis results will be saved.")
    return parser.parse_args()


def get_top_features(model, feature_names, n=10):
    """Safely extracts top features from different pipeline structures."""
    try:
        # If it's a pipeline, get the classifier and the selector
        if isinstance(model, Pipeline):
            clf = model.named_steps['clf']
            selector = model.named_steps['selector']
            mask = selector.get_support()
            current_features = feature_names[mask]
        else:
            clf = model
            current_features = feature_names

        # Extract weights/importance
        if hasattr(clf, 'feature_importances_'):
            weights = clf.feature_importances_
        elif hasattr(clf, 'coef_'):
            weights = abs(clf.coef_[0])
        else:
            return ["N/A"] * n

        top_indices = weights.argsort()[-n:][::-1]
        return current_features[top_indices].tolist()
    except Exception as e:
        logger.error(f"Error extracting features: {e}")
        return ["Error"] * n


def main():
    # Parse the arguments
    args = parse_args()
    report_path = args.report
    output_folder = args.output_folder

    # Build the output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)
    
    # Initialize a logger in the output folder
    logger.add(os.path.join(output_folder, "analyze_reports.log"), level="INFO")

    # Load the report
    df_report = pd.read_csv(report_path)

    # Build a subject column:
    df_report["subject"] = df_report["lesion_mask_file"].apply(lambda x: str(x).split("/")[-1].split("_")[0])

    # Print the features extracted for each lesion:
    logger.info(f"Features extracted for each lesion: {df_report.columns.tolist()} \n")

    # # Split the dataset per subject into train 80% and test 20%:
    # subjects = df_report["subject"].unique()
    # train_subjects = subjects[:int(0.8 * len(subjects))]
    # test_subjects = subjects[int(0.8 * len(subjects)):]

    # Remove columns 'lesion_label', 'scan_file' and 'lesion_mask_file'
    df_report = df_report.drop(columns=["lesion_label", "scan_file", "lesion_mask_file"])

    # Keep columns ending with mean and columns lesion_size, critical_lesion_label and subject
    columns_to_keep = [col for col in df_report.columns if col.endswith("mean") or col in ["lesion_size", "critical_lesion_label", "subject"]]
    df_report = df_report[columns_to_keep]

    # We analyze the number of subjects, the number of critical lesions
    num_subjects = df_report["subject"].nunique()
    num_critical_lesions = df_report["critical_lesion_label"].sum()
    total_lesions = len(df_report)
    logger.info(f"Number of subjects: {num_subjects}")
    logger.info(f"Number of critical lesions: {num_critical_lesions}")
    logger.info(f"Total number of lesions: {total_lesions}")
    logger.info(f"Percentage of critical lesions: {num_critical_lesions / total_lesions:.2%} \n")


    ### Statistical analysis of the features:
    # For each feature, T-test between critical and non-critical lesions:
    feature_columns = [col for col in df_report.columns if col not in ["critical_lesion_label", "subject"]]
    ttest_results = []
    for feature in feature_columns:
        critical_values = df_report[df_report["critical_lesion_label"] == 1][feature]
        non_critical_values = df_report[df_report["critical_lesion_label"] == 0][feature]
        t_stat, p_value = ttest_ind(critical_values, non_critical_values, nan_policy='omit')
        ttest_results.append((feature, t_stat, p_value))

    # Sort by p-value:
    ttest_results.sort(key=lambda x: x[2])
    
    # Log the t-test results in a table:
    ttest_table = prettytable.PrettyTable(["Feature", "T-statistic", "P-value", "Significant (p < 0.05)"])
    for feature, t_stat, p_value in ttest_results:
        is_significant = p_value < 0.05
        ttest_table.add_row([feature, f"{t_stat:.4f}", f"{p_value:.4f}", "✓" if is_significant else ""])
    logger.info("T-test results for each feature:\n" + str(ttest_table))

    # We train the classifier on the train set and evaluate it on the test set
    groups = df_report["subject"]
    X = df_report.drop(columns=["critical_lesion_label", "subject"])
    y = df_report["critical_lesion_label"]
    
    models_base = {
        "A: Random Forest": RandomForestClassifier(random_state=42),
        "B: Logistic Regression (L1)": Pipeline([
            ('scaler', StandardScaler()),
            ('selector', SelectKBest(f_classif, k=20)), 
            ('clf', LogisticRegression(l1_ratio=1, solver='liblinear', random_state=42))
        ]),
        "C: Linear SVM": Pipeline([
            ('scaler', StandardScaler()),
            ('selector', SelectKBest(f_classif, k=20)),
            ('clf', SVC(kernel='linear', random_state=42))
        ]),
        "D: Gradient Boosting": GradientBoostingClassifier(random_state=42)
    }

    # Initialize the GroupKFold splitter
    gkf = GroupKFold(n_splits=5)
    results_table = prettytable.PrettyTable(["Method", "Accuracy", "Recall", "F1", "ROC-AUC"])

    # Initialize most important features:
    top_features_dict = {}

    for name, model in models_base.items():
        # cv=5 means we split the 95 samples into 5 groups and test on each
        gkf = GroupKFold(n_splits=5)
        scores = cross_validate(
            model, X, y,
            groups=groups, 
            cv=gkf,
            scoring=['accuracy', 'recall', 'f1', 'roc_auc'])
        results_table.add_row([name, f"{scores['test_accuracy'].mean():.4f} ± {scores['test_accuracy'].std():.4f}",
                               f"{scores['test_recall'].mean():.4f} ± {scores['test_recall'].std():.4f}",
                               f"{scores['test_f1'].mean():.4f} ± {scores['test_f1'].std():.4f}",
                               f"{scores['test_roc_auc'].mean():.4f} ± {scores['test_roc_auc'].std():.4f}"])
        
        # For each model, we want to print the top features
        model.fit(X, y)
        top_features_dict[name] = get_top_features(model, X.columns)
        
    # Log the results
    logger.info(results_table)

    # Feature Importance Table
    feat_table = prettytable.PrettyTable(["Rank"] + list(models_base.keys()))
    for i in range(10):
        row = [i+1] + [top_features_dict[m][i] if i < len(top_features_dict[m]) else "" for m in models_base]
        feat_table.add_row(row)
    
    logger.info("\nTop 10 Features per Model:\n" + str(feat_table))


if __name__ == "__main__":
    main()