"""
This script loads all the reports generated by the detection of critical lesions and analyzes them to identify the most common features of critical lesions.

Input:
    --report: path to the generated report (csv file)
    -o: path to the output folder where the analysis results will be saved.

Author: Pierre-Louis Benveniste
"""
import os
import argparse
import pandas as pd
from loguru import logger
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import GroupKFold, cross_validate
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from skopt import BayesSearchCV
from skopt.space import Integer, Real, Categorical
import prettytable
from scipy.stats import ttest_ind
from sklearn.metrics import accuracy_score, recall_score, f1_score, roc_auc_score
import numpy as np
from sklearn.calibration import calibration_curve
from tqdm import tqdm
from scipy.interpolate import interp1d
import shap


def parse_args():
    parser = argparse.ArgumentParser(description="Analyze the reports generated by the detection of critical lesions to identify the most common features of critical lesions.")
    parser.add_argument("--report", type=str, required=True, help="Path to the generated report (csv file)")
    parser.add_argument("-o", "--output_folder", type=str, required=True, help="Path to the output folder where the analysis results will be saved.")
    return parser.parse_args()


def get_top_features(model, feature_names, n=10):
    """Safely extracts top features from different pipeline structures."""
    try:
        # If it's a pipeline, check for selector and classifier
        if isinstance(model, Pipeline):
            clf = model.named_steps['clf']
            # Check if 'selector' exists in the pipeline steps
            if 'selector' in model.named_steps:
                selector = model.named_steps['selector']
                mask = selector.get_support()
                current_features = feature_names[mask]
            else:
                # No selector, use all features
                current_features = feature_names
        else:
            clf = model
            current_features = feature_names

        # Extract weights/importance
        if hasattr(clf, 'feature_importances_'):
            weights = clf.feature_importances_
        elif hasattr(clf, 'coef_'):
            # For linear models like Logistic Regression or Linear SVM
            weights = np.abs(clf.coef_[0])
        else:
            return ["N/A"] * n

        # Ensure we don't try to get more features than we have
        n = min(n, len(current_features))
        
        top_indices = weights.argsort()[-n:][::-1]
        return current_features[top_indices].tolist()
    except Exception as e:
        logger.error(f"Error extracting features: {e}")
        return ["Error"] * n


def main():
    # Parse the arguments
    args = parse_args()
    report_path = args.report
    output_folder = args.output_folder

    # Build the output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)
    
    # Initialize a logger in the output folder
    path_logger = os.path.join(output_folder, "analyze_reports.log")
    if os.path.exists(path_logger):
        os.remove(path_logger)
    logger.add(os.path.join(output_folder, "analyze_reports.log"), level="INFO")

    # Load the report
    df_report = pd.read_csv(report_path)

    # Build a subject column:
    df_report["subject"] = df_report["lesion_mask_file"].apply(lambda x: str(x).split("/")[-1].split("_")[0])

    # Print the features extracted for each lesion:
    # logger.info(f"Features extracted for each lesion: {df_report.columns.tolist()} \n")

    # # Split the dataset per subject into train 80% and test 20%:
    # subjects = df_report["subject"].unique()
    # train_subjects = subjects[:int(0.8 * len(subjects))]
    # test_subjects = subjects[int(0.8 * len(subjects)):]
    
    # We analyze the number of subjects, the number of critical lesions
    num_subjects = df_report["subject"].nunique()
    num_critical_lesions = df_report["critical_lesion_label"].sum()
    total_lesions = len(df_report)
    logger.info(f"Number of subjects: {num_subjects}")
    logger.info(f"Total number of lesions: {total_lesions}")
    logger.info(f"Number of critical lesions: {num_critical_lesions}")
    logger.info(f"Percentage of critical lesions: {num_critical_lesions / total_lesions:.2%} \n")

    # Remove columns 'lesion_label', 'scan_file' and 'lesion_mask_file'
    df_report = df_report.drop(columns=["lesion_label", "scan_file", "lesion_mask_file"])

    # Remove features with (diff_with_hc_norm) in their name:
    diff_with_hc_columns = [col for col in df_report.columns if "diff_with_hc_norm" in col]
    df_report = df_report.drop(columns=diff_with_hc_columns)

    # Print the number of features extracted for each lesion
    logger.info(f"Number of features extracted for each lesion: {len(df_report.columns) - 2} \n") # We remove the subject and the critical_lesion_label columns

    # Keep columns ending with mean and columns lesion_size, critical_lesion_label and subject
    # columns_to_keep = [col for col in df_report.columns if col.endswith("mean") or col in ["lesion_size", "critical_lesion_label", "subject"]]
    # df_report = df_report[columns_to_keep]

    # Removal of constant columns
    constant_columns = df_report.columns[df_report.nunique() <= 1].tolist()
    logger.info(f"Columns with constant values: {constant_columns} \n")
    # Remove columns with constant values
    df_report = df_report.drop(columns=constant_columns)
    logger.info(f"Number of features after removing constant columns: {len(df_report.columns) - 2} \n") # We remove the subject and the critical_lesion_label columns

    # Print names of columns which have nan values:
    nan_columns = df_report.columns[df_report.isna().any()].tolist()
    # logger.info(f"Columns with NaN values: {nan_columns} \n")
    # Replace NaN values with the mean of each column except for the subject column:
    for col in nan_columns:
        if col != "subject":
            df_report[col] = df_report[col].fillna(df_report[col].mean())

    # ### Statistical analysis of the features:
    # # For each feature, T-test between critical and non-critical lesions:
    # feature_columns = [col for col in df_report.columns if col not in ["critical_lesion_label", "subject"]]
    # ttest_results = []
    # for feature in feature_columns:
    #     critical_values = df_report[df_report["critical_lesion_label"] == 1][feature]
    #     non_critical_values = df_report[df_report["critical_lesion_label"] == 0][feature]
    #     t_stat, p_value = ttest_ind(critical_values, non_critical_values)
    #     ttest_results.append((feature, t_stat, p_value))

    # # Sort by p-value:
    # ttest_results.sort(key=lambda x: x[2])
    
    # # Log the t-test results in a table:
    # ttest_table = prettytable.PrettyTable(["Feature", "T-statistic", "P-value", "Significant (p < 0.05)"])
    # for feature, t_stat, p_value in ttest_results:
    #     is_significant = p_value < 0.05
    #     ttest_table.add_row([feature, f"{t_stat:.4f}", f"{p_value:.4f}", "✓" if is_significant else ""])
    # logger.info("T-test results for each feature:\n" + str(ttest_table))

    # We train the classifier on the train set and evaluate it on the test set
    groups = df_report["subject"]
    X = df_report.drop(columns=["critical_lesion_label", "subject"])
    y = df_report["critical_lesion_label"]
    
    # models_base = {
    #     "A: Random Forest": RandomForestClassifier(random_state=42),
    #     "B: Logistic Regression (L1)": Pipeline([
    #         ('scaler', StandardScaler()),
    #         ('selector', SelectKBest(f_classif, k=20)), 
    #         ('clf', LogisticRegression(l1_ratio=1, solver='liblinear', random_state=42))
    #     ]),
    #     "C: Linear SVM": Pipeline([
    #         ('scaler', StandardScaler()),
    #         ('selector', SelectKBest(f_classif, k=20)),
    #         ('clf', SVC(kernel='linear', random_state=42))
    #     ]),
    #     "D: Gradient Boosting": GradientBoostingClassifier(random_state=42)
    # }

    # # Initialize the GroupKFold splitter
    # gkf = GroupKFold(n_splits=5)
    # results_table = prettytable.PrettyTable(["Method", "Accuracy", "Recall", "F1", "ROC-AUC"])

    # # Initialize most important features:
    # top_features_dict = {}

    # for name, model in models_base.items():
    #     # cv=5 means we split the 95 samples into 5 groups and test on each
    #     scores = cross_validate(
    #         model, X, y,
    #         groups=groups, 
    #         cv=gkf,
    #         scoring=['accuracy', 'recall', 'f1', 'roc_auc'])
    #     results_table.add_row([name, f"{scores['test_accuracy'].mean():.4f} ± {scores['test_accuracy'].std():.4f}",
    #                            f"{scores['test_recall'].mean():.4f} ± {scores['test_recall'].std():.4f}",
    #                            f"{scores['test_f1'].mean():.4f} ± {scores['test_f1'].std():.4f}",
    #                            f"{scores['test_roc_auc'].mean():.4f} ± {scores['test_roc_auc'].std():.4f}"])
        
    #     # For each model, we want to print the top features
    #     model.fit(X, y)
    #     top_features_dict[name] = get_top_features(model, X.columns)
        
    # # Log the results
    # logger.info(results_table)

    # # Feature Importance Table
    # feat_table = prettytable.PrettyTable(["Rank"] + list(models_base.keys()))
    # for i in range(10):
    #     row = [i+1] + [top_features_dict[m][i] if i < len(top_features_dict[m]) else "" for m in models_base]
    #     feat_table.add_row(row)
    
    # logger.info("\nTop 10 Features per Model:\n" + str(feat_table))

    logger.info(f"Dataset: {len(X)} lesions, {X.shape[1]} features, {groups.nunique()} subjects.")

    # Define Model Configurations and Bayesian Search Spaces
    # Note: Using 'clf__' prefix to target the classifier step in the pipeline
    model_configs = [
        # {
        #     "name": "Random Forest",
        #     "pipeline": Pipeline([('clf', RandomForestClassifier(random_state=42))]),
        #     "search_space": {
        #         'clf__n_estimators': Integer(50, 300),
        #         'clf__max_depth': Integer(3, 15),
        #         'clf__min_samples_split': Integer(2, 10)
        #     }
        # },
        # {
        #     "name": "Logistic Regression",
        #     "pipeline": Pipeline([
        #         ('scaler', StandardScaler()),
        #         ('selector', SelectKBest(f_classif)),
        #         ('clf', LogisticRegression(solver='liblinear', penalty='l1', random_state=42))
        #     ]),
        #     "search_space": {
        #         'selector__k': Integer(10, min(X.shape[1], 50)),
        #         'clf__C': Real(1e-3, 1e2, prior='log-uniform')
        #     }
        # },
        # {
        #     "name": "Linear SVM",
        #     "pipeline": Pipeline([
        #         ('scaler', StandardScaler()),
        #         ('selector', SelectKBest(f_classif)),
        #         ('clf', SVC(kernel='linear', probability=True, random_state=42))
        #     ]),
        #     "search_space": {
        #         'selector__k': Integer(10, min(X.shape[1], 50)),
        #         'clf__C': Real(1e-3, 1e2, prior='log-uniform')
        #     }
        # },
        {
            "name": "Gradient Boosting",
            "pipeline": Pipeline([('clf', XGBClassifier(random_state=42))]),
            "search_space": {
                'clf__learning_rate': Real(0.01, 0.3, prior='log-uniform'),
                'clf__max_depth': Integer(3, 10),
                'clf__subsample': Real(0.5, 1),
            }
        }
    ]

    outer_cv = GroupKFold(n_splits=5)
    inner_cv = GroupKFold(n_splits=3)
    
    summary_table = prettytable.PrettyTable(["Model", "Accuracy", "Recall", "F1", "ROC-AUC"])
    
    for config in model_configs:
        logger.info(f"Starting Nested CV for {config['name']}...")
        
        outer_scores = {'acc': [], 'rec': [], 'f1': [], 'auc': []}

        calibration_curves = []
        
        # Outer Loop
        for train_idx, test_idx in tqdm(outer_cv.split(X, y, groups=groups), desc=f"Outer CV - {config['name']}", total=outer_cv.get_n_splits()):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
            groups_train = groups.iloc[train_idx]
            
            # Inner Loop: Bayesian Optimization
            bayes_search = BayesSearchCV(
                estimator=config['pipeline'],
                search_spaces=config['search_space'],
                cv=inner_cv,
                n_iter=20, # Number of parameter settings sampled
                scoring='f1',
                n_jobs=-1,
                random_state=42
            )
            
            # Fit nested search
            bayes_search.fit(X_train, y_train, groups=groups_train)
            
            # Evaluate on unseen outer fold
            best_model = bayes_search.best_estimator_
            y_pred = best_model.predict(X_test)
            y_prob = best_model.predict_proba(X_test)[:, 1]
            
            outer_scores['acc'].append(accuracy_score(y_test, y_pred))
            outer_scores['rec'].append(recall_score(y_test, y_pred))
            outer_scores['f1'].append(f1_score(y_test, y_pred))
            outer_scores['auc'].append(roc_auc_score(y_test, y_prob))

            # Get the calibration curve for this fold
            prob_true, prob_pred = calibration_curve(y_test, y_prob, n_bins=10)
            calibration_curves.append((prob_true, prob_pred))

        # Log Mean Results
        summary_table.add_row([
            config['name'],
            f"{np.mean(outer_scores['acc']):.3f} ± {np.std(outer_scores['acc']):.3f}",
            f"{np.mean(outer_scores['rec']):.3f} ± {np.std(outer_scores['rec']):.3f}",
            f"{np.mean(outer_scores['f1']):.3f} ± {np.std(outer_scores['f1']):.3f}",
            f"{np.mean(outer_scores['auc']):.3f} ± {np.std(outer_scores['auc']):.3f}"
        ])

        # Final fit on all data to get "Global" top features
        final_search = BayesSearchCV(config['pipeline'], config['search_space'], cv=inner_cv, n_iter=20, random_state=42)
        final_search.fit(X, y, groups=groups)
        best_params = final_search.best_params_
        top_feats = get_top_features(final_search.best_estimator_, X.columns)
        logger.info(f"Top features for {config['name']}: {top_feats}")

        logger.info(f"Best parameters for {config['name']}: {best_params}")
        # best_params = {'clf__learning_rate': 0.040343472274915984, 'clf__max_depth': 8, 'clf__subsample': 0.966433999423917}

        model = XGBClassifier(**{k.replace('clf__', ''): v for k, v in best_params.items()}, random_state=42)
        model.fit(X, y)
        # Get shap values and plot them
        explainer = shap.Explainer(model, seed=42)
        shap_values = explainer(X)
        plt.figure(figsize=(20, 20))
        shap.plots.waterfall(shap_values[0])
        plt.title('SHAP summary plot for the final model (features renamed)')
        plt.savefig(os.path.join(output_folder, 'shap_summary.png'))
        plt.close()

        # Define a common x range limited strictly to [0, 1]
        x_common = np.linspace(0, 1, 100)

        interpolated_curves = []
        for prob_true, prob_pred in calibration_curves:
            # Ensure sorting of the calibration points
            order = np.argsort(prob_pred)
            prob_pred = np.array(prob_pred)[order]
            prob_true = np.array(prob_true)[order]

            # Bound the interpolation domain to [min, max] and avoid extrapolation
            interp_func = interp1d(
                prob_pred, prob_true,
                kind="linear",
                bounds_error=False,
                fill_value=(prob_true[0], prob_true[-1])
            )
            y_interp = interp_func(x_common)
            # Clip to [0,1] in case of minor numerical drift
            y_interp = np.clip(y_interp, 0, 1)
            interpolated_curves.append(y_interp)

        mean_prob_true = np.mean(interpolated_curves, axis=0)

        # Plot the mean calibration curve
        plt.figure()
        plt.plot(x_common, mean_prob_true, marker='.', label='Mean calibration')
        plt.plot([0, 1], [0, 1], linestyle='--', label='Perfect calibration')
        plt.xlabel('Predicted probability')
        plt.ylabel('True probability')
        plt.title('Mean Calibration curve across folds')
        plt.legend()
        plt.savefig(os.path.join(output_folder, f'mean_calibration_{config["name"]}.png'))
        plt.close()

    logger.info("\nAnalysis Complete.\n" + str(summary_table))


if __name__ == "__main__":
    main()