"""
This script detects critical lesions in MRI scans.
It takes as scan as input and outputs the detected "critical" lesions with their locations and sizes.

Input:
    -i: Path to the MRI scan (NIfTI format)
    --pam50: Path to the PAM50 template folder containing all the csv files
    -o: Path to the output folder

Output:
    None

Author: Pierre-Louis Benveniste
"""
import argparse
import os
from pdb import run
import nibabel as nib
import numpy as np
from scipy import ndimage
import pandas as pd
from generate_csa_plot import load_normative_data, load_single_subject_data, create_lineplot, create_lineplot_asymetry


def parse_arguments():
    parser = argparse.ArgumentParser(description="Detect critical lesions in MRI scans.")
    parser.add_argument("-i", "--input", required=True, help="Path to the MRI scan (NIfTI format)")
    parser.add_argument("--pam50", required=True, help="Path to the PAM50 template folder containing all the csv files")
    parser.add_argument("-o", "--output_folder", required=True, help="Path to the output folder")
    return parser.parse_args()


def run_lesion_segmentation(input_scan, sc_mask, output_path, qc_folder):

    # Build the lesion mask output path
    lesion_mask = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-lesion_seg.nii.gz"))
    
    # Run the SCT command
    if os.path.exists(lesion_mask):
        return lesion_mask
    
    assert os.system(f"SCT_USE_GPU=1 sct_deepseg lesion_ms -i {input_scan} -o {lesion_mask} -qc {qc_folder} -qc-seg {sc_mask} -qc-plane Axial" ) == 0, "Error running the lesion segmentation model"

    return lesion_mask


def run_sc_segmentation(input_scan, output_path, qc_folder):

    # Build the SC mask output path
    sc_mask = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-SC_seg.nii.gz"))
    
    # Run the SCT command
    if os.path.exists(sc_mask):
        return sc_mask

    assert os.system(f"SCT_USE_GPU=1 sct_deepseg spinalcord -i {input_scan} -o {sc_mask} -qc {qc_folder}") == 0, "Error running the SC segmentation model"

    return sc_mask


def run_vert_labeling(input_scan, output_path, qc_folder):

    # Build the vertebral labeling output path
    out_files = os.path.join(output_path, "out.nii.gz")
    vert_levels = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-discs_dlabel.nii.gz"))


    if os.path.exists(vert_levels):
        return vert_levels
    
    # Run the SCT command
    assert os.system(f"SCT_USE_GPU=1 sct_deepseg spine -i {input_scan} -o {out_files} -qc {qc_folder}") == 0, "Error running the vertebral labeling model"

    # Remove the file out_totalspineseg_all.json and out_totalspineseg_all.nii.gz generated by the command
    assert os.system(f"rm {os.path.join(output_path, 'out_totalspineseg_all.json')}") == 0, "Error removing the out_totalspineseg_all.json file"
    assert os.system(f"rm {os.path.join(output_path, 'out_totalspineseg_all.nii.gz')}") == 0, "Error removing the out_totalspineseg_all.nii.gz file"
    
    # Rename the output file out_totalspineseg_discs.nii.gz to the desired name (same for json)
    assert os.system(f"mv {os.path.join(output_path, 'out_totalspineseg_discs.nii.gz')} {vert_levels}") == 0, "Error renaming the out_totalspineseg_discs.nii.gz file"
    assert os.system(f"mv {os.path.join(output_path, 'out_totalspineseg_discs.json')} {vert_levels.replace(".nii.gz", ".json")}") == 0, "Error renaming the out_totalspineseg_discs.json file"

    return vert_levels


def get_lesion_stats(lesion_mask):
    """
    This function loads the lesion mask and computes the statistics of each lesion (CoM and size).
    Input:
        lesion_mask: Path to the lesion mask (NIfTI format)
    Output:
        A list of dictionaries containing the statistics of each lesion (CoM and size)
    """
    # Initialize the output dict
    lesion_stats = []

    # Load the lesion mask array
    lesion_mask = nib.load(lesion_mask)
    lesion_array = lesion_mask.get_fdata()

    # Get the unique lesion labels
    s = ndimage.generate_binary_structure(3,3)
    # Label connected components (lesions)
    labeled_lesions, num_lesions = ndimage.label(lesion_array, structure=s)
    # Get voxel volume
    voxel_volume = np.prod(lesion_mask.header.get_zooms())

    # Get orientation
    orientation = nib.aff2axcodes(lesion_mask.affine)
    IF_axis_index = orientation.index('I') if 'I' in orientation else (orientation.index('S') if 'S' in orientation else None)

    # For each lesion, compute its CoM and size
    for lesion_label in range(1, num_lesions + 1):
        lesion_mask = labeled_lesions == lesion_label
        # Lesion size
        lesion_size = float(np.sum(lesion_mask)*voxel_volume)
        # Lesion CoM in voxel coordinates
        lesion_com = ndimage.center_of_mass(lesion_mask)
        lesion_com = (float(lesion_com[0]), float(lesion_com[1]), float(lesion_com[2]))
        # We compute a list of all ax slices where the lesion is present
        lesion_slices = set(np.where(lesion_mask)[IF_axis_index].tolist())
        lesion_stats.append({"label": lesion_label, "size": lesion_size, "CoM": lesion_com, "slices": lesion_slices})

    return lesion_stats


def compute_normalized_csa(sc_mask, vert_levels, output_path, qc_folder):
    """
    This function computes the spinal cord CSA at each vertebral level and normalizes it based on the PAM50 template.

    Input:
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        vert_levels: Path to the vertebral labeling (NIfTI format)
    Output:
        A dictionary containing the atrophy results (mean cross-sectional area at each vertebral level)
    """
    # Build output csv path
    output_csv = os.path.join(output_path, "csa.csv")

    if os.path.exists(output_csv):
        return output_csv

    # Run the SCT command to compute atrophy
    assert os.system(f"sct_process_segmentation -i {sc_mask} -discfile {vert_levels} -perslice 1 -normalize-PAM50 1 -o {output_csv} -qc {qc_folder}") == 0, "Error running the sct_compute_atrophy command"

    return output_csv


def plot_csa(norm_csa_file, pam_50_csa_folder, output_path):
    """
    Detect atrophies by comparing the normalized CSA with the PAM50 template.
    Input:
        norm_csa_file: Path to the normalized CSA file
        pam_50_csa_folder: Path to the PAM50 template folder containing all the csv files
        output_path: Path to the output folder
    Output:
        A list of detected atrophies
    """
    # Build output plot path
    path_csa_plot = os.path.join(output_path, "csa_plot.png")

    if os.path.exists(path_csa_plot):
        return path_csa_plot

    # Load the subject normalized CSA data
    df_sub, min_slice_idx, max_slice_idx = load_single_subject_data(norm_csa_file)   

    # Load spine-generic normative data
    path_HC = os.path.join(pam_50_csa_folder, "spinal_cord")
    path_participants_tsv = os.path.join(pam_50_csa_folder, "participants.tsv")
    df_normative_data = load_normative_data(path_HC, path_participants_tsv, min_slice=min_slice_idx, max_slice=max_slice_idx)
   
    subject_id = output_path.split("/")[-1]
    number_of_subjects = len(df_normative_data['participant_id'].unique())

    # Create the plots
    create_lineplot(df_normative_data, df_sub, subject_id, number_of_subjects, path_csa_plot) 
    
    return path_csa_plot


def compute_asymmetry(image, sc_mask, vert_levels, output_path, qc_folder):
    """
    This function computes the asymmetry of the spinal cord at each vertebral level.
    Input:
        image: Path to the input image (NIfTI format)
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        vert_levels: Path to the vertebral labeling (NIfTI format)
        output_path: Path to the output folder
    Output:
        output_csv: Path to the output csv file containing the asymmetry results
    """

    # Build output csv path
    output_csv = os.path.join(output_path, "asymmetry.csv")

    if os.path.exists(output_csv):
        return output_csv

    # Run asymmetry computation
    assert os.system(f"sct_process_segmentation -i {sc_mask} -anat {image} -perslice 1 -qc {qc_folder} -o {output_csv} -v 2 -discfile {vert_levels}") == 0, "Error running the sct_compute_asymmetry command"

    # Add the following columns
    df_asymmetry = pd.read_csv(output_csv)
    # We create the ratio columns for the anterior and posterior quadrants
    df_asymmetry["RATIO(area_quadrant_anterior_left/right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] / df_asymmetry["MEAN(area_quadrant_anterior_right)"]
    df_asymmetry["RATIO(area_quadrant_posterior_left/right)"] = df_asymmetry["MEAN(area_quadrant_posterior_left)"] / df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    # We create the difference columns for the anterior and posterior quadrants
    df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] - df_asymmetry["MEAN(area_quadrant_anterior_right)"]
    df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["MEAN(area_quadrant_posterior_left)"] - df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    # We create a normalized difference column for the anterior and posterior quadrants (difference divided by the mean of the two quadrants)
    df_asymmetry["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_anterior_left)"]
    df_asymmetry["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_posterior_left)"]
    
    # Save the updated dataframe to the same csv file
    df_asymmetry.to_csv(output_csv, index=False)

    return output_csv


def plot_asymmetry(asymmetry_csv, lesion_statistics, output_path):
    """
    This function plots the asymmetry results.
    Input:
        asymmetry_csv: Path to the csv file containing the asymmetry results
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    path_asymmetry_plot = os.path.join(output_path, "asymmetry_plot.png")

    # if os.path.exists(path_asymmetry_plot):
    #     return path_asymmetry_plot
    
    # Load the asymmetry results
    df_asymmetry = pd.read_csv(asymmetry_csv)
    # Get subject ID from output path
    subject_id = output_path.split("/")[-1]
    # Create the plot
    create_lineplot_asymetry(df_asymmetry, subject_id, path_asymmetry_plot, lesion_statistics)

    return path_asymmetry_plot


def detect_laterality(image, lesion_mask, sc_mask, discs_levels, output_path, qc_folder):
    """
    This function detects the laterality of the lesions based on the sct_analyze_lesion command.
    Inspiration 
    Input:
        image: Path to the input image (NIfTI format)
        lesion_mask: Path to the lesion mask (NIfTI format)
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        discs_levels: Path to the vertebral labeling (NIfTI format)
        output_path: Path to the output folder
        qc_folder: Path to the quality control folder
    Output:
        A report containing the laterality of each lesion
    """
    # Build template_folder
    template_folder = os.path.join(output_path, "template_folder")
    os.makedirs(template_folder, exist_ok=True)

    # if os.path.exists(output_report):
    #     return output_report

    # Register to template
    registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=hog,iter=10:step=2,type=seg,algo=bsplinesyn,slicewise=1"
    assert os.system(f"sct_register_to_template -i {image} -s {sc_mask} -ldisc {discs_levels} -ref subject -param {registration_param} -c t2 -ofolder {template_folder} -qc {qc_folder}") == 0, "Error running the sct_register_to_template command"
    
    # Warp atlas to the subject space
    path_template = os.path.join(template_folder, "warp_template2anat.nii.gz")
    assert os.system(f"sct_warp_template -d {image} -w {path_template} -ofolder {template_folder} -qc {qc_folder}") == 0, "Error running the sct_warp_template command"

    # Atlas-based lesion analysis
    assert os.system(f"sct_analyze_lesion -m {lesion_mask} -s {sc_mask} -f {template_folder} -perslice 1 -qc {qc_folder}") == 0, "Error running the sct_analyze_lesion command"

    return None


def detect_critical_lesions(input_scan, output_path, pam_50_csa_folder):

    # Build the output folder
    image_name = input_scan.split("/")[-1].replace(".nii.gz", "")
    output_path = os.path.join(output_path, image_name)
    os.makedirs(output_path, exist_ok=True)
    qc_folder = os.path.join(output_path, "qc")
    os.makedirs(qc_folder, exist_ok=True)

    # Placeholder for the actual lesion detection logic
    print(f"Detecting critical lesions in scan: {input_scan}")
    # Copy img to output folder
    assert os.system(f"cp {input_scan} {output_path}") == 0, "Error copying the input scan to the output folder"
    # SC segmentation
    sc_mask = run_sc_segmentation(input_scan, output_path, qc_folder)
    # Vert labeling
    vert_levels =run_vert_labeling(input_scan, output_path, qc_folder)
    # Lesion segmentation
    lesion_mask = run_lesion_segmentation(input_scan, sc_mask, output_path, qc_folder)
    
    # For each lesion, we compute its CoM and size
    lesion_statistics = get_lesion_stats(lesion_mask)

    # Now we investigate the detection of spinal cord atrophy
    norm_csa_file = compute_normalized_csa(sc_mask, vert_levels, output_path, qc_folder)

    # Now we plot the CSA compared to the PAM50
    path_csa_plot = plot_csa(norm_csa_file, pam_50_csa_folder, output_path)

    # Now we perform asymetry computation
    asymetry_csv = compute_asymmetry(input_scan, sc_mask, vert_levels, output_path, qc_folder)

    # Plot asymetry
    path_asymmetry_plot = plot_asymmetry(asymetry_csv, lesion_statistics, output_path)

    # Detect laterality
    laterality_report = detect_laterality(input_scan, lesion_mask, sc_mask, vert_levels, output_path, qc_folder)


if __name__ == "__main__":
    args = parse_arguments()
    detect_critical_lesions(args.input, args.output_folder, args.pam50)