"""
This script detects critical lesions in MRI scans.
It takes as scan as input and outputs the detected "critical" lesions with their locations and sizes.

Input:
    -i: Path to the MRI scan (NIfTI format)
    --lesion-seg: Path to the lesion segmentation mask (NIfTI format)
    --age: age of the subject (used for atrophy detection)
    --sex: sex of the subject (used for atrophy detection)
    --pam50: Path to the PAM50 template folder containing all the csv files
    -o: Path to the output folder

Output:
    None

Author: Pierre-Louis Benveniste
"""
import argparse
from datetime import datetime
import os
from pdb import run
import nibabel as nib
import numpy as np
from scipy import ndimage
import pandas as pd
import json
from generate_csa_plot import load_normative_data, load_single_subject_data, create_lineplot, create_lineplot_asymetry, create_lineplot_asymetry_with_hc, load_normative_data_asymmetry, create_lineplot_laterality


def parse_arguments():
    parser = argparse.ArgumentParser(description="Detect critical lesions in MRI scans.")
    parser.add_argument("-i", "--input", required=True, help="Path to the MRI scan (NIfTI format)")
    parser.add_argument("--lesion-seg", help="Path to the lesion segmentation mask (NIfTI format)")
    parser.add_argument("--date-birth", required=True, type=str, help="Date of birth of the subject YYYYMMDD")
    parser.add_argument("--sex", required=True, choices=["M", "F"], help="Sex of the subject (used for atrophy detection)")
    parser.add_argument("--pam50", help="Path to the PAM50 template folder containing all the csv files")
    parser.add_argument("--hc-data", required=True, help="Path to the healthy control data folder for asymmetry comparison")
    parser.add_argument("-o", "--output_folder", required=True, help="Path to the output folder")
    return parser.parse_args()


def run_lesion_segmentation(input_scan, sc_mask, lesion_mask_input, output_path, qc_folder):

    # Build the lesion mask output path
    lesion_mask = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-lesion_seg.nii.gz"))

    if lesion_mask_input is not None:
        # Copy the lesion mask input to the lesion mask output path
        os.system(f"cp {lesion_mask_input} {lesion_mask}")
    
    # Run the SCT command
    if os.path.exists(lesion_mask):
        return lesion_mask
    
    assert os.system(f"SCT_USE_GPU=1 sct_deepseg lesion_ms -i {input_scan} -o {lesion_mask} -qc {qc_folder} -qc-seg {sc_mask} -qc-plane Axial" ) == 0, "Error running the lesion segmentation model"

    return lesion_mask


def run_sc_segmentation(input_scan, output_path, qc_folder):

    # Build the SC mask output path
    sc_mask = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-SC_seg.nii.gz"))
    
    # Run the SCT command
    if os.path.exists(sc_mask):
        return sc_mask

    assert os.system(f"SCT_USE_GPU=1 sct_deepseg spinalcord -i {input_scan} -o {sc_mask} -qc {qc_folder}") == 0, "Error running the SC segmentation model"

    return sc_mask


def run_vert_labeling(input_scan, output_path, qc_folder):

    # Build the vertebral labeling output path
    out_files = os.path.join(output_path, "out.nii.gz")
    vert_levels = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-discs_dlabel.nii.gz"))


    if os.path.exists(vert_levels):
        return vert_levels
    
    # Run the SCT command
    assert os.system(f"SCT_USE_GPU=1 sct_deepseg spine -i {input_scan} -o {out_files} -qc {qc_folder}") == 0, "Error running the vertebral labeling model"

    # Remove the file out_totalspineseg_all.json and out_totalspineseg_all.nii.gz generated by the command
    assert os.system(f"rm {os.path.join(output_path, 'out_totalspineseg_all.json')}") == 0, "Error removing the out_totalspineseg_all.json file"
    assert os.system(f"rm {os.path.join(output_path, 'out_totalspineseg_all.nii.gz')}") == 0, "Error removing the out_totalspineseg_all.nii.gz file"
    
    # Rename the output file out_totalspineseg_discs.nii.gz to the desired name (same for json)
    assert os.system(f"mv {os.path.join(output_path, 'out_totalspineseg_discs.nii.gz')} {vert_levels}") == 0, "Error renaming the out_totalspineseg_discs.nii.gz file"
    assert os.system(f"mv {os.path.join(output_path, 'out_totalspineseg_discs.json')} {vert_levels.replace(".nii.gz", ".json")}") == 0, "Error renaming the out_totalspineseg_discs.json file"

    return vert_levels


def get_lesion_stats(input_lesion_mask_path, sc_mask, image, vert_levels, output_path, qc_folder):
    """
    This function loads the lesion mask and computes the statistics of each lesion (CoM and size).
    Input:
        lesion_mask: Path to the lesion mask (NIfTI format)
    Output:
        A list of dictionaries containing the statistics of each lesion (CoM and size)
    """
    # Build the lesion stats output path
    lesion_stats_path = os.path.join(output_path, "lesion_stats.json")

    # If the lesion stats file already exists, we load it and return it
    if os.path.exists(lesion_stats_path):
        with open(lesion_stats_path, "r") as f:
            lesion_stats = json.load(f)
        return lesion_stats

    # Build a folder where lesions masks will be saved (one mask per lesion)
    one_lesion_per_mask_folder = os.path.join(output_path, "one_lesion_per_mask")
    os.makedirs(one_lesion_per_mask_folder, exist_ok=True)

    # We also build a temp folder to save intermediate files generated by the sct_process_segmentation command
    temp_folder = os.path.join(output_path, "temp_lesion_stats")
    os.makedirs(temp_folder, exist_ok=True)

    # Initialize the output dict
    lesion_stats = []

    # Load the lesion mask array
    all_lesion_mask = nib.load(input_lesion_mask_path)
    lesion_array = all_lesion_mask.get_fdata()

    # Get the unique lesion labels
    s = ndimage.generate_binary_structure(3,3)
    # Label connected components (lesions)
    labeled_lesions, num_lesions = ndimage.label(lesion_array, structure=s)
    # Get voxel volume
    voxel_volume = np.prod(all_lesion_mask.header.get_zooms())

    # Get orientation
    orientation = nib.aff2axcodes(all_lesion_mask.affine)
    IF_axis_index = orientation.index('I') if 'I' in orientation else (orientation.index('S') if 'S' in orientation else None)

    # For each lesion, compute its CoM and size
    for lesion_label in range(1, num_lesions + 1):
        lesion_mask = labeled_lesions == lesion_label
        # Lesion size
        lesion_size = float(np.sum(lesion_mask)*voxel_volume)
        # Lesion CoM in voxel coordinates
        lesion_com = ndimage.center_of_mass(lesion_mask)
        lesion_com = (float(lesion_com[0]), float(lesion_com[1]), float(lesion_com[2]))
        # We compute a list of all ax slices where the lesion is present
        lesion_slices = list(set(np.where(lesion_mask)[IF_axis_index].tolist()))

        # For each lesion, we compute the slices indexes in the PAM-50 template
        ## We save one mask per lesion in the temp folder
        lesion_mask_nifti = nib.Nifti1Image(lesion_mask.astype(np.uint8), all_lesion_mask.affine, all_lesion_mask.header)
        lesion_mask_path = os.path.join(one_lesion_per_mask_folder, input_lesion_mask_path.split("/")[-1].replace(".nii.gz", f"_lesion_{lesion_label}.nii.gz"))
        nib.save(lesion_mask_nifti, lesion_mask_path)
        ## We label the spinal cord:
        assert os.system(f"sct_label_vertebrae -i {image} -s {sc_mask} -discfile {vert_levels} -c t2 -qc {qc_folder} -ofolder {temp_folder}") == 0, "Error running the sct_label_vertebrae command"
        ## We process the lesion segmentation
        sc_mask_labeled = os.path.join(temp_folder, os.path.basename(sc_mask).replace(".nii.gz", "_labeled.nii.gz"))
        output_csv = os.path.join(temp_folder, f"lesion_{lesion_label}_PAM50.csv")

        # If the lesion segmentation spends only one slice, we need to dilate by one slice in S-I axis
        if len(lesion_slices) == 1:
            # dilation is 0x0x1 if dilating index is 2, else it is 0x1x0 if dilating index is 1, else it is 1x0x0 if dilating index is 0
            if IF_axis_index == 2: dilation = "0x0x1"
            elif IF_axis_index == 1: dilation = "0x1x0"
            else: dilation = "1x0x0"
            temp_dilated_lesion_mask = os.path.join(temp_folder, os.path.basename(lesion_mask_path).replace(".nii.gz", "_dilated.nii.gz"))
            assert os.system(f"sct_maths -i {lesion_mask_path} -shape ball -dilate {dilation} -o {temp_dilated_lesion_mask}") == 0, "Error running the sct_maths command to dilate the lesion mask"
            # Then we process the segmentation with the dilated lesion mask to get the PAM50 slices corresponding
            assert os.system(f"sct_process_segmentation -i {temp_dilated_lesion_mask} -vertfile {sc_mask_labeled} -perslice 1 -normalize-PAM50 1 -o {output_csv}") == 0, "Error running the sct_process_segmentation command"
        
        else:
            assert os.system(f"sct_process_segmentation -i {lesion_mask_path} -vertfile {sc_mask_labeled} -perslice 1 -normalize-PAM50 1 -o {output_csv}") == 0, "Error running the sct_process_segmentation command"
        ## Load the output csv file and extract the slices where the lesion is present
        df_lesion = pd.read_csv(output_csv)
        lesion_slices_pam50 = df_lesion[df_lesion["MEAN(area)"] > 0]["Slice (I->S)"].tolist()
        lesion_slices_pam50 = sorted(lesion_slices_pam50)
        lesion_slices_pam50 = list(set(lesion_slices_pam50))
        ## If we had previously dilated the lesion mask, we need to remove some slices from the lesion_slices_pam50
        if len(lesion_slices) == 1:
            # We have to remove the first 1/3 and last 1/3 of the lesion_slices_pam50 to be sure to keep only the slices corresponding to the original lesion mask
            lesion_slices_pam50 = lesion_slices_pam50[len(lesion_slices_pam50)//3: -len(lesion_slices_pam50)//3]
        
        lesion_stats.append({"label": lesion_label, "size": lesion_size, "CoM": lesion_com, "slices": lesion_slices, "slices_pam50": lesion_slices_pam50})

    # Remove the temp folder
    os.system(f"rm -rf {temp_folder}")

    # Save the lesion statistics to a json file
    with open(lesion_stats_path, "w") as f:
        json.dump(lesion_stats, f)

    return lesion_stats


def compute_pam50_normalized_csa(sc_mask, vert_levels, output_path, qc_folder):
    """
    This function computes the spinal cord CSA at each vertebral level and translates to the PAM50 template.

    Input:
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        vert_levels: Path to the vertebral labeling (NIfTI format)
    Output:
        A dictionary containing the atrophy results (mean cross-sectional area at each vertebral level)
    """
    # Build output csv path
    output_csv = os.path.join(output_path, "csa.csv")

    if os.path.exists(output_csv):
        return output_csv

    # Run the SCT command to compute atrophy
    assert os.system(f"sct_process_segmentation -i {sc_mask} -discfile {vert_levels} -perslice 1 -normalize-PAM50 1 -o {output_csv} -qc {qc_folder}") == 0, "Error running the sct_compute_atrophy command"

    return output_csv


def filter_normative_data(df_normative_data, sex, age):
    """
    This functions filters the normative data to keep only the subjects:
        - of the same sex
        - in the same 10-year age group (if nobody in the same 10-year age group, we keep the closest age group (for example if a subject is 71 and nobody is between 70 and 80, we keep the subjects between 60 and 70 or between 80 and 90 depending on which group has the closest mean age to the subject's age))
    Input:
        - df_normative_data: Dataframe containing the normative data for the healthy control group
        - sex
        - age
    Output:
        - df_normative_data_filtered: Dataframe containing the filtered normative data for the healthy control group
        - age_group: the age group that was kept (either the same 10-year age group or the closest one)
    """
    # 1. Filter by sex first
    df_filtered = df_normative_data[df_normative_data['sex'] == sex].copy()
    # 2. Define the target 10-year age group (e.g., 71 -> [70, 80))
    lower_bound = (age // 10) * 10
    upper_bound = lower_bound + 10
    # Attempt to filter for the specific age group
    df_target_group = df_filtered[
        (df_filtered['age'] >= lower_bound) & 
        (df_filtered['age'] < upper_bound)
    ]
    # 3. Fallback logic: If no subjects in the 10th age group
    if df_target_group.empty:
        # Create a helper column to identify decades
        df_filtered['decade'] = (df_filtered['age'] // 10) * 10
        # Calculate the mean age of each available decade group
        group_means = df_filtered.groupby('decade')['age'].mean()
        # Find the decade whose mean age is closest to the subject's age
        closest_decade = (group_means - age).abs().idxmin()
        df_target_group = df_filtered[df_filtered['decade'] == closest_decade]
        age_group = f"{closest_decade}-{closest_decade + 10}"

    else:
        age_group = f"{lower_bound}-{upper_bound}"
    
    return df_target_group.drop(columns=['decade'], errors='ignore'), age_group


def normalize_outside_lesion(df_normative_data, df_sub, lesion_statistics, path_out_csv, asymmetry=False):
    """
    This function normalizes the subject's CSA values with the healthy control group and plots the normalized values.
    The subject's values are already in the PAM50 space. 
    We want to bring the mean and std to that of the HC data but we want to compute the normalization on areas outside of the lesion to avoid normalizing with pathological values.
    Input:
        df_normative_data: Dataframe containing the normative data for the healthy control group
        df_sub: Dataframe containing the subject's data in the PAM50 space
        lesion_statistics: List of dictionaries containing lesion statistics
        path_out_csv: Path to the output CSV file
    Output:
        df_sub_normalized: Dataframe containing the subject's normalized data in the PAM50 space
    """
    # Get the slices corresponding to the lesions in the PAM50 space
    lesion_slices_pam50 = []
    for lesion in lesion_statistics:
        lesion_slices_pam50.extend(lesion["slices_pam50"])
    # Get all the slides of the subject in the PAM50 space
    subject_slices_pam50 = df_sub["Slice (I->S)"].tolist()
    # Build slices to use for normalization by keeping only the slices that are not in the lesion_slices_pam50
    slices_for_normalization = [slice for slice in subject_slices_pam50 if slice not in lesion_slices_pam50]
    
    # We normlaize the following metrics:
    METRICS = ['MEAN(area)', 'MEAN(diameter_AP)', 'MEAN(diameter_RL)', 'MEAN(compression_ratio)', 'MEAN(eccentricity)',
           'MEAN(solidity)']
    
    if asymmetry:
        METRICS = ['MEAN(symmetry_dice_RL)', 'MEAN(symmetry_hausdorff_RL)', 'MEAN(symmetry_difference_RL)',
                    'MEAN(symmetry_dice_AP)', 'MEAN(symmetry_hausdorff_AP)', 'MEAN(symmetry_difference_AP)',
                    'NORM_DIFF(area_quadrant_anterior_left-right)', 'NORM_DIFF(area_quadrant_posterior_left-right)',
                    'NORM_DIFF(area_left-right)']
    
    df_sub_normalized = df_sub.copy()
    # For each metric, we compute the mean and std of the normative data on the slices outside of the lesion but in subject
    for metric in METRICS:
        normative_mean = df_normative_data[df_normative_data["Slice (I->S)"].isin(slices_for_normalization)][metric].mean()
        normative_std = df_normative_data[df_normative_data["Slice (I->S)"].isin(slices_for_normalization)][metric].std()
        # We normalize the subject's metric by bringing the mean and std to that of the normative data
        df_sub_normalized[metric] = (df_sub[metric] - df_sub[metric].mean()) / df_sub[metric].std() * normative_std + normative_mean
    
    # Save the normalized subject data to a new csv file
    df_sub_normalized.to_csv(path_out_csv, index=False)

    return df_sub_normalized


def plot_csa(pam50_norm_csa_file, sex, age, hc_data, lesion_statistics, output_path):
    """
    Detect atrophies by comparing the PAM50-normalized CSA with the PAM50 template.
    Input:
        pam50_norm_csa_file: Path to the PAM50-normalized CSA file
        sex: Sex of the subject (used for atrophy detection)
        age: Age of the subject (used for atrophy detection)
        hc_data: Path to the healthy control data folder
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        A list of detected atrophies
    """
    # Build output plot path
    path_csa_plot = os.path.join(output_path, "csa_plot.png")
    path_csa_plot_normalized = os.path.join(output_path, "csa_plot_normalized.png")

    if os.path.exists(path_csa_plot):
        return path_csa_plot

    # Load the subject normalized CSA data
    df_sub, min_slice_idx, max_slice_idx = load_single_subject_data(pam50_norm_csa_file)   

    # Load spine-generic normative data
    path_HC = hc_data
    path_participants_tsv = os.path.join(hc_data, "participants.tsv")
    df_normative_data = load_normative_data(path_HC, path_participants_tsv, min_slice=min_slice_idx, max_slice=max_slice_idx)
    # Get the subject ID and the nb of subjects
    subject_id = output_path.split("/")[-1]
    # Filter the normative data to keep only the subjects of the same sex and age group
    df_normative_data_filtered, age_group = filter_normative_data(df_normative_data, sex, age)
    number_of_subjects = len(df_normative_data_filtered['participant_id'].unique())

    # Create the plots
    create_lineplot(df_normative_data_filtered, df_sub, subject_id, number_of_subjects, path_csa_plot, lesion_statistics, sex, age_group)

    #### Normalization fo the metrics values with the healthy control group and plot the normalized values
    path_csv_normalized = os.path.join(output_path, "csa_normalized.csv")
    df_sub_normalized = normalize_outside_lesion(df_normative_data_filtered, df_sub, lesion_statistics, path_csv_normalized)

    # Now we create another plot after the normalization
    create_lineplot(df_normative_data_filtered, df_sub_normalized, subject_id, number_of_subjects, path_csa_plot_normalized, lesion_statistics, sex, age_group)

    return path_csa_plot


def compute_asymmetry(image, sc_mask, vert_levels, output_path, qc_folder, pam50_normalization=False):
    """
    This function computes the asymmetry of the spinal cord at each vertebral level.
    Input:
        image: Path to the input image (NIfTI format)
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        vert_levels: Path to the vertebral labeling (NIfTI format)
        output_path: Path to the output folder
    Output:
        output_csv: Path to the output csv file containing the asymmetry results
    """

    # Build output csv path
    if pam50_normalization:
        output_csv = os.path.join(output_path, "asymmetry_normalized_pam50.csv")
    else:
        output_csv = os.path.join(output_path, "asymmetry.csv")

    if os.path.exists(output_csv):
        return output_csv
    
    if pam50_normalization:
        normalization_flag = "-normalize-PAM50 1"
    else:
        normalization_flag = ""

    # Run asymmetry computation
    assert os.system(f"sct_process_segmentation -i {sc_mask} -anat {image} -perslice 1 -qc {qc_folder} -o {output_csv} -discfile {vert_levels} {normalization_flag}") == 0, "Error running the sct_compute_asymmetry command"

    # Add the following columns
    df_asymmetry = pd.read_csv(output_csv)
    # We create the ratio columns for the anterior and posterior quadrants
    df_asymmetry["RATIO(area_quadrant_anterior_left/right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] / df_asymmetry["MEAN(area_quadrant_anterior_right)"]
    df_asymmetry["RATIO(area_quadrant_posterior_left/right)"] = df_asymmetry["MEAN(area_quadrant_posterior_left)"] / df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    # We create the difference columns for the anterior and posterior quadrants
    df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] - df_asymmetry["MEAN(area_quadrant_anterior_right)"]
    df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["MEAN(area_quadrant_posterior_left)"] - df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    # We create a normalized difference column for the anterior and posterior quadrants (difference divided by the mean of the two quadrants)
    df_asymmetry["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_anterior_left)"]
    df_asymmetry["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_posterior_left)"]
    
    # Save the updated dataframe to the same csv file
    df_asymmetry.to_csv(output_csv, index=False)

    return output_csv


def plot_asymmetry(asymmetry_csv, lesion_statistics, output_path):
    """
    This function plots the asymmetry results.
    Input:
        asymmetry_csv: Path to the csv file containing the asymmetry results
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    path_asymmetry_plot = os.path.join(output_path, "asymmetry_plot.png")

    if os.path.exists(path_asymmetry_plot):
        return path_asymmetry_plot
    
    # Load the asymmetry results
    df_asymmetry = pd.read_csv(asymmetry_csv)
    # Get subject ID from output path
    subject_id = output_path.split("/")[-1]
    # Create the plot
    create_lineplot_asymetry(df_asymmetry, subject_id, path_asymmetry_plot, lesion_statistics)

    return path_asymmetry_plot


def plot_asymmetry_with_hc(asymmetry_csv, sex, age, path_hc_data, lesion_statistics, output_path):
    """
    This function plots the asymmetry results compared to a healthy control group.
    Input:
        asymmetry_csv: Path to the csv file containing the asymmetry results
        sex: Sex of the subject
        age: Age of the subject
        path_hc_data: Path to the healthy control data folder for asymmetry comparison
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    path_asymmetry_plot_hc = os.path.join(output_path, "asymmetry_plot_hc.png")
    path_asymmetry_plot_hc_normalized = os.path.join(output_path, "asymmetry_plot_hc_normalized.png")

    if os.path.exists(path_asymmetry_plot_hc):
        return path_asymmetry_plot_hc
    
    # Load the asymmetry results
    df_asymmetry = pd.read_csv(asymmetry_csv)
    # We create a normalized difference column for the anterior and posterior quadrants (difference divided by the mean of the two quadrants)
    df_asymmetry["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_anterior_left)"]
    df_asymmetry["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_posterior_left)"]
    df_asymmetry["DIFF(area_left-right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] + df_asymmetry["MEAN(area_quadrant_posterior_left)"] - df_asymmetry["MEAN(area_quadrant_anterior_right)"] - df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    df_asymmetry["NORM_DIFF(area_left-right)"] = df_asymmetry["DIFF(area_left-right)"] / (df_asymmetry["MEAN(area_quadrant_anterior_left)"] + df_asymmetry["MEAN(area_quadrant_posterior_left)"])
    # Get subject ID from output path
    subject_id = output_path.split("/")[-1]
    # Get min and max slice index from the asymmetry csv to load only the relevant slices from the healthy control data
    min_slice_idx = df_asymmetry["Slice (I->S)"].min()
    max_slice_idx = df_asymmetry["Slice (I->S)"].max()

    data_tsv = os.path.join(path_hc_data, "participants.tsv")
    
    # Load healthy control data
    df_hc = load_normative_data(path_hc_data, data_tsv, min_slice=min_slice_idx, max_slice=max_slice_idx)
    # We create the diff columns for the healthy control group as well
    df_hc["DIFF(area_quadrant_anterior_left-right)"] = df_hc["MEAN(area_quadrant_anterior_left)"] - df_hc["MEAN(area_quadrant_anterior_right)"]
    df_hc["DIFF(area_quadrant_posterior_left-right)"] = df_hc["MEAN(area_quadrant_posterior_left)"] - df_hc["MEAN(area_quadrant_posterior_right)"]
    df_hc["DIFF(area_left-right)"] = df_hc["MEAN(area_quadrant_anterior_left)"] + df_hc["MEAN(area_quadrant_posterior_left)"] - df_hc["MEAN(area_quadrant_anterior_right)"] - df_hc["MEAN(area_quadrant_posterior_right)"]
    # We create the norm diff columns for the healthy control group as well
    df_hc["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_hc["DIFF(area_quadrant_anterior_left-right)"] / df_hc["MEAN(area_quadrant_anterior_left)"]
    df_hc["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_hc["DIFF(area_quadrant_posterior_left-right)"] / df_hc["MEAN(area_quadrant_posterior_left)"]
    df_hc["NORM_DIFF(area_left-right)"] = df_hc["DIFF(area_left-right)"] / (df_hc["MEAN(area_quadrant_anterior_left)"] + df_hc["MEAN(area_quadrant_posterior_left)"])

    # Filter the healthy control data to keep only the subjects of the same sex and age group
    df_hc_filtered, age_group = filter_normative_data(df_hc, sex, age)

    # Create the plot
    create_lineplot_asymetry_with_hc(df_asymmetry, sex, age, df_hc_filtered, subject_id, path_asymmetry_plot_hc, lesion_statistics, age_group)

    #### Normalization fo the metrics values with the healthy control group and plot the normalized values
    path_csv_normalized = os.path.join(output_path, "asymmetry_normalized.csv")
    df_asymmetry_normalized = normalize_outside_lesion(df_hc_filtered, df_asymmetry, lesion_statistics, path_csv_normalized, asymmetry=True)

    # Now we create another plot after the normalization
    create_lineplot_asymetry_with_hc(df_asymmetry_normalized, sex, age, df_hc_filtered, subject_id, path_asymmetry_plot_hc_normalized, lesion_statistics, age_group)


    return path_asymmetry_plot_hc


def detect_laterality(image, lesion_mask, sc_mask, discs_levels, lesion_statistics, output_path, qc_folder):
    """
    This function detects the laterality of the lesions based on the sct_analyze_lesion command.
    We run the command for each lesion separately to get the laterality of each lesion.
    We do this because we want to be sure that the lesion we indexed as 1 before is the same lesion indexed as 1 by sct_analyze_lesion.
    Inspiration: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/5049

    Input:
        image: Path to the input image (NIfTI format)
        lesion_mask: Path to the lesion mask (NIfTI format)
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        discs_levels: Path to the vertebral labeling (NIfTI format)
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
        qc_folder: Path to the quality control folder
    Output:
        A report containing the laterality of each lesion
    """
    # Build laterality_folder
    laterality_folder = os.path.join(output_path, "laterality_outputs")
    os.makedirs(laterality_folder, exist_ok=True)

    # Build output report path
    laterality_report_folder = os.path.join(output_path, "laterality_report")
    if os.path.exists(laterality_report_folder):
        return laterality_report_folder
    # Or we build it
    os.makedirs(laterality_report_folder, exist_ok=True)

    # Here we chose the vert levels to keep:
    disc_level_data = nib.load(discs_levels).get_fdata()
    unique_labels = np.unique(disc_level_data).tolist()
    unique_labels = [int(label) for label in unique_labels if label != 0] # Remove background label
    # We want to select the level at 3 and 7 if they are present in the unique labels, else, we select the 25% and 75% quantiles of the unique labels
    first_level = 3 if 3 in unique_labels else int(np.quantile(unique_labels, 0.25))
    second_level = 7 if 7 in unique_labels else int(np.quantile(unique_labels, 0.75))
    print(f"Unique vertebral levels found: {unique_labels}. We will keep the levels {first_level} and {second_level} for the laterality analysis.")

    # Keep only vert 3 and 7 
    disc_levels_only_2 = os.path.join(output_path, discs_levels.replace(".nii.gz", "_only_2.nii.gz"))
    assert os.system(f"sct_label_utils -i {discs_levels} -o {disc_levels_only_2} -keep {first_level},{second_level}") == 0, "Error running the sct_label_utils command to keep only vert 3 and 7"

    # Register to template
    # registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=20"
    # registration_param = "step=1,type=seg,algo=centermass:step=2,type=seg,algo=bsplinesyn,metric=CC,iter=10,smooth=1,slicewise=1"
    registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=0"
    # registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=1"
    # registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=seg,algo=bsplinesyn,iter=5,slicewise=1,metric=CC,smooth=1:step=3,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=1"
    assert os.system(f"sct_register_to_template -i {image} -s {sc_mask} -ldisc {disc_levels_only_2} -param {registration_param} -c t2 -ofolder {laterality_folder} -qc {qc_folder}") == 0, "Error running the sct_register_to_template command"
    
    # Warp atlas to the subject space
    path_template = os.path.join(laterality_folder, "warp_template2anat.nii.gz")
    assert os.system(f"sct_warp_template -d {image} -w {path_template} -ofolder {laterality_folder} -qc {qc_folder}") == 0, "Error running the sct_warp_template command"

    # We perform analysis lesion by lesion:
    ## We save one mask per lesion
    for lesion in lesion_statistics:
        ## Build the path to the lesion mask
        lesion_mask_path = os.path.join(output_path, "one_lesion_per_mask", lesion_mask.split("/")[-1].replace(".nii.gz", f"_lesion_{lesion['label']}.nii.gz"))
        # Atlas-based lesion analysis
        assert os.system(f"sct_analyze_lesion -m {lesion_mask_path} -s {sc_mask} -f {laterality_folder} -perslice 1 -ofolder {laterality_report_folder}") == 0, "Error running the sct_analyze_lesion command"

    return laterality_report_folder


def plot_laterality(laterality_report_folder, lesion_mask, lesion_statistics, output_path):
    """
    This function plots the laterality results.
    Input:
        laterality_report: Path to the laterality report generated by the sct_analyze_lesion command
        lesion_mask: Path to the lesion mask (NIfTI format)
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    laterality_plot = os.path.join(output_path, "laterality_plot.png")

    if os.path.exists(laterality_plot):
        return laterality_plot

    # Initialize the dataframe of laterality funiculi for each lesion
    df_laterality = pd.DataFrame(columns=["Slice (I->S)", "lesion_label", "white matter", "gray matter", "dorsal columns", "lateral funiculi", "ventral funiculi", "total % (all tracts)", "vert_level"])

    # Load the laterality report
    # There is one report per lesion in the xlsx file:
    for lesion in lesion_statistics:
        lesion_label = lesion["label"]
        xlsx_path = os.path.join(laterality_report_folder, lesion_mask.split("/")[-1].replace(".nii.gz", f"_lesion_{lesion_label}_analysis.xlsx")) 
        # We load the report and extract the laterality information
        xls = pd.ExcelFile(xlsx_path)
        ## We only keep page: lesion#1_distribution
        df_lesion = pd.read_excel(xls, 'lesion#1_distribution')
        # Remove the last line corresponding to the total lesion volume
        df_lesion = df_lesion[:-1]
        # Create a Slice (I->S)	column in df_laterality equal to the index
        df_lesion["Slice (I->S)"] = df_lesion.index
        ## Add this df to the df_laterality dataframe with the lesion label as index
        df_lesion["lesion_label"] = lesion_label
        df_laterality = pd.concat([df_laterality, df_lesion[["Slice (I->S)", "vert_level", "lesion_label", "white matter", "gray matter", "dorsal columns", "lateral funiculi", "ventral funiculi", "total % (all tracts)"]]], ignore_index=True)
    
    # Rename the vert_level column to VertLevel
    df_laterality = df_laterality.rename(columns={"vert_level": "VertLevel"})

    # Plot the laterality results
    sub_ID = output_path.split("/")[-1]
    create_lineplot_laterality(df_laterality, sub_ID, laterality_plot)

    return laterality_plot


def detect_critical_lesions(input_scan, sex, date_birth, output_path, path_hc_data, lesion_mask_input=None):

    # Build the output folder
    image_name = input_scan.split("/")[-1].replace(".nii.gz", "")
    output_path = os.path.join(output_path, image_name)
    os.makedirs(output_path, exist_ok=True)
    qc_folder = os.path.join(output_path, "qc")
    os.makedirs(qc_folder, exist_ok=True)

    # Get scan date
    scan_date = datetime.strptime(input_scan.split("/")[-1].split("_")[1].split("-")[1], "%Y%m%d")
    age = int((scan_date - datetime.strptime(date_birth, "%Y%m%d")).days / 365.25)

    # Placeholder for the actual lesion detection logic
    print(f"Detecting critical lesions in scan: {input_scan}")
    # Copy img to output folder
    assert os.system(f"cp {input_scan} {output_path}") == 0, "Error copying the input scan to the output folder"
    # SC segmentation
    sc_mask = run_sc_segmentation(input_scan, output_path, qc_folder)
    # Vert labeling
    vert_levels =run_vert_labeling(input_scan, output_path, qc_folder)
    # Lesion segmentation
    lesion_mask = run_lesion_segmentation(input_scan, sc_mask, lesion_mask_input, output_path, qc_folder)
    
    # For each lesion, we compute its CoM and size
    lesion_statistics = get_lesion_stats(lesion_mask, sc_mask, input_scan, vert_levels,output_path, qc_folder)

    # Now we investigate the detection of spinal cord atrophy
    pam50_normalized_csa_file = compute_pam50_normalized_csa(sc_mask, vert_levels, output_path, qc_folder)

    # Now we plot the CSA compared to the PAM50
    path_csa_plot = plot_csa(pam50_normalized_csa_file, sex, age, path_hc_data, lesion_statistics, output_path)

    # # Now we perform asymetry computation
    # asymetry_csv = compute_asymmetry(input_scan, sc_mask, vert_levels, output_path, qc_folder)

    # # Plot asymetry
    # path_asymmetry_plot = plot_asymmetry(asymetry_csv, lesion_statistics, output_path)

    # Now compute asymetry with PAM50 normalization to be able to compare with healthy controls
    asymetry_csv_pam50 = compute_asymmetry(input_scan, sc_mask, vert_levels, output_path, qc_folder, pam50_normalization=True)
    
    # Plot asymetry with HC group
    path_asymmetry_plot_hc = plot_asymmetry_with_hc(asymetry_csv_pam50, sex, age, path_hc_data, lesion_statistics, output_path)

    # Detect laterality
    laterality_report_folder = detect_laterality(input_scan, lesion_mask, sc_mask, vert_levels, lesion_statistics, output_path, qc_folder)

    # Plot laterality results
    laterality_plot = plot_laterality(laterality_report_folder, lesion_mask, lesion_statistics, output_path)


if __name__ == "__main__":
    args = parse_arguments()
    detect_critical_lesions(args.input, args.sex, args.date_birth, args.output_folder, args.hc_data, lesion_mask_input=args.lesion_seg)