"""
This script detects critical lesions in MRI scans.
It takes as scan as input and outputs the detected "critical" lesions with their locations and sizes.

Input:
    -i: Path to the MRI scan (NIfTI format)
    --pam50: Path to the PAM50 template folder containing all the csv files
    -o: Path to the output folder

Output:
    None

Author: Pierre-Louis Benveniste
"""
import argparse
import os
from pdb import run
import nibabel as nib
import numpy as np
from scipy import ndimage
import pandas as pd
import json
from generate_csa_plot import load_normative_data, load_single_subject_data, create_lineplot, create_lineplot_asymetry, create_lineplot_asymetry_with_hc, load_normative_data_asymmetry, create_lineplot_laterality


def parse_arguments():
    parser = argparse.ArgumentParser(description="Detect critical lesions in MRI scans.")
    parser.add_argument("-i", "--input", required=True, help="Path to the MRI scan (NIfTI format)")
    parser.add_argument("--pam50", required=True, help="Path to the PAM50 template folder containing all the csv files")
    parser.add_argument("--hc-data", required=True, help="Path to the healthy control data folder for asymmetry comparison")
    parser.add_argument("-o", "--output_folder", required=True, help="Path to the output folder")
    return parser.parse_args()


def run_lesion_segmentation(input_scan, sc_mask, output_path, qc_folder):

    # Build the lesion mask output path
    lesion_mask = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-lesion_seg.nii.gz"))
    
    # Run the SCT command
    if os.path.exists(lesion_mask):
        return lesion_mask
    
    assert os.system(f"SCT_USE_GPU=1 sct_deepseg lesion_ms -i {input_scan} -o {lesion_mask} -qc {qc_folder} -qc-seg {sc_mask} -qc-plane Axial" ) == 0, "Error running the lesion segmentation model"

    return lesion_mask


def run_sc_segmentation(input_scan, output_path, qc_folder):

    # Build the SC mask output path
    sc_mask = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-SC_seg.nii.gz"))
    
    # Run the SCT command
    if os.path.exists(sc_mask):
        return sc_mask

    assert os.system(f"SCT_USE_GPU=1 sct_deepseg spinalcord -i {input_scan} -o {sc_mask} -qc {qc_folder}") == 0, "Error running the SC segmentation model"

    return sc_mask


def run_vert_labeling(input_scan, output_path, qc_folder):

    # Build the vertebral labeling output path
    out_files = os.path.join(output_path, "out.nii.gz")
    vert_levels = os.path.join(output_path, input_scan.split("/")[-1].replace(".nii.gz", "_label-discs_dlabel.nii.gz"))


    if os.path.exists(vert_levels):
        return vert_levels
    
    # Run the SCT command
    assert os.system(f"SCT_USE_GPU=1 sct_deepseg spine -i {input_scan} -o {out_files} -qc {qc_folder}") == 0, "Error running the vertebral labeling model"

    # Remove the file out_totalspineseg_all.json and out_totalspineseg_all.nii.gz generated by the command
    assert os.system(f"rm {os.path.join(output_path, 'out_totalspineseg_all.json')}") == 0, "Error removing the out_totalspineseg_all.json file"
    assert os.system(f"rm {os.path.join(output_path, 'out_totalspineseg_all.nii.gz')}") == 0, "Error removing the out_totalspineseg_all.nii.gz file"
    
    # Rename the output file out_totalspineseg_discs.nii.gz to the desired name (same for json)
    assert os.system(f"mv {os.path.join(output_path, 'out_totalspineseg_discs.nii.gz')} {vert_levels}") == 0, "Error renaming the out_totalspineseg_discs.nii.gz file"
    assert os.system(f"mv {os.path.join(output_path, 'out_totalspineseg_discs.json')} {vert_levels.replace(".nii.gz", ".json")}") == 0, "Error renaming the out_totalspineseg_discs.json file"

    return vert_levels


def get_lesion_stats(input_lesion_mask_path, sc_mask, image, vert_levels, output_path, qc_folder):
    """
    This function loads the lesion mask and computes the statistics of each lesion (CoM and size).
    Input:
        lesion_mask: Path to the lesion mask (NIfTI format)
    Output:
        A list of dictionaries containing the statistics of each lesion (CoM and size)
    """
    # Build the lesion stats output path
    lesion_stats_path = os.path.join(output_path, "lesion_stats.json")

    # If the lesion stats file already exists, we load it and return it
    if os.path.exists(lesion_stats_path):
        with open(lesion_stats_path, "r") as f:
            lesion_stats = json.load(f)
        return lesion_stats

    # Build a folder where lesions masks will be saved (one mask per lesion)
    one_lesion_per_mask_folder = os.path.join(output_path, "one_lesion_per_mask")
    os.makedirs(one_lesion_per_mask_folder, exist_ok=True)

    # We also build a temp folder to save intermediate files generated by the sct_process_segmentation command
    temp_folder = os.path.join(output_path, "temp_lesion_stats")
    os.makedirs(temp_folder, exist_ok=True)

    # Initialize the output dict
    lesion_stats = []

    # Load the lesion mask array
    all_lesion_mask = nib.load(input_lesion_mask_path)
    lesion_array = all_lesion_mask.get_fdata()

    # Get the unique lesion labels
    s = ndimage.generate_binary_structure(3,3)
    # Label connected components (lesions)
    labeled_lesions, num_lesions = ndimage.label(lesion_array, structure=s)
    # Get voxel volume
    voxel_volume = np.prod(all_lesion_mask.header.get_zooms())

    # Get orientation
    orientation = nib.aff2axcodes(all_lesion_mask.affine)
    IF_axis_index = orientation.index('I') if 'I' in orientation else (orientation.index('S') if 'S' in orientation else None)

    # For each lesion, compute its CoM and size
    for lesion_label in range(1, num_lesions + 1):
        lesion_mask = labeled_lesions == lesion_label
        # Lesion size
        lesion_size = float(np.sum(lesion_mask)*voxel_volume)
        # Lesion CoM in voxel coordinates
        lesion_com = ndimage.center_of_mass(lesion_mask)
        lesion_com = (float(lesion_com[0]), float(lesion_com[1]), float(lesion_com[2]))
        # We compute a list of all ax slices where the lesion is present
        lesion_slices = list(set(np.where(lesion_mask)[IF_axis_index].tolist()))

        # For each lesion, we compute the slices indexes in the PAM-50 template
        ## We save one mask per lesion in the temp folder
        lesion_mask_nifti = nib.Nifti1Image(lesion_mask.astype(np.uint8), all_lesion_mask.affine, all_lesion_mask.header)
        lesion_mask_path = os.path.join(one_lesion_per_mask_folder, input_lesion_mask_path.split("/")[-1].replace(".nii.gz", f"_lesion_{lesion_label}.nii.gz"))
        nib.save(lesion_mask_nifti, lesion_mask_path)
        ## We label the spinal cord:
        assert os.system(f"sct_label_vertebrae -i {image} -s {sc_mask} -discfile {vert_levels} -c t2 -qc {qc_folder} -ofolder {temp_folder}") == 0, "Error running the sct_label_vertebrae command"
        ## We process the lesion segmentation
        sc_mask_labeled = os.path.join(temp_folder, os.path.basename(sc_mask).replace(".nii.gz", "_labeled.nii.gz"))
        output_csv = os.path.join(temp_folder, f"lesion_{lesion_label}_PAM50.csv")
        assert os.system(f"sct_process_segmentation -i {lesion_mask_path} -vertfile {sc_mask_labeled} -perslice 1 -normalize-PAM50 1 -o {output_csv}") == 0, "Error running the sct_process_segmentation command"
        ## Load the output csv file and extract the slices where the lesion is present
        df_lesion = pd.read_csv(output_csv)
        lesion_slices_pam50 = df_lesion[df_lesion["MEAN(area)"] > 0]["Slice (I->S)"].tolist()
        lesion_slices_pam50 = list(set(lesion_slices_pam50))
        lesion_stats.append({"label": lesion_label, "size": lesion_size, "CoM": lesion_com, "slices": lesion_slices, "slices_pam50": lesion_slices_pam50})

    # Remove the temp folder
    os.system(f"rm -rf {temp_folder}")

    # Save the lesion statistics to a json file
    with open(lesion_stats_path, "w") as f:
        json.dump(lesion_stats, f)

    return lesion_stats


def compute_normalized_csa(sc_mask, vert_levels, output_path, qc_folder):
    """
    This function computes the spinal cord CSA at each vertebral level and normalizes it based on the PAM50 template.

    Input:
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        vert_levels: Path to the vertebral labeling (NIfTI format)
    Output:
        A dictionary containing the atrophy results (mean cross-sectional area at each vertebral level)
    """
    # Build output csv path
    output_csv = os.path.join(output_path, "csa.csv")

    if os.path.exists(output_csv):
        return output_csv

    # Run the SCT command to compute atrophy
    assert os.system(f"sct_process_segmentation -i {sc_mask} -discfile {vert_levels} -perslice 1 -normalize-PAM50 1 -o {output_csv} -qc {qc_folder}") == 0, "Error running the sct_compute_atrophy command"

    return output_csv


def plot_csa(norm_csa_file, pam_50_csa_folder, output_path):
    """
    Detect atrophies by comparing the normalized CSA with the PAM50 template.
    Input:
        norm_csa_file: Path to the normalized CSA file
        pam_50_csa_folder: Path to the PAM50 template folder containing all the csv files
        output_path: Path to the output folder
    Output:
        A list of detected atrophies
    """
    # Build output plot path
    path_csa_plot = os.path.join(output_path, "csa_plot.png")

    if os.path.exists(path_csa_plot):
        return path_csa_plot

    # Load the subject normalized CSA data
    df_sub, min_slice_idx, max_slice_idx = load_single_subject_data(norm_csa_file)   

    # Load spine-generic normative data
    path_HC = os.path.join(pam_50_csa_folder, "spinal_cord")
    path_participants_tsv = os.path.join(pam_50_csa_folder, "participants.tsv")
    df_normative_data = load_normative_data(path_HC, path_participants_tsv, min_slice=min_slice_idx, max_slice=max_slice_idx)
   
    subject_id = output_path.split("/")[-1]
    number_of_subjects = len(df_normative_data['participant_id'].unique())

    # Create the plots
    create_lineplot(df_normative_data, df_sub, subject_id, number_of_subjects, path_csa_plot) 
    
    return path_csa_plot


def compute_asymmetry(image, sc_mask, vert_levels, output_path, qc_folder, pam50_normalization=False):
    """
    This function computes the asymmetry of the spinal cord at each vertebral level.
    Input:
        image: Path to the input image (NIfTI format)
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        vert_levels: Path to the vertebral labeling (NIfTI format)
        output_path: Path to the output folder
    Output:
        output_csv: Path to the output csv file containing the asymmetry results
    """

    # Build output csv path
    if pam50_normalization:
        output_csv = os.path.join(output_path, "asymmetry_normalized_pam50.csv")
    else:
        output_csv = os.path.join(output_path, "asymmetry.csv")

    if os.path.exists(output_csv):
        return output_csv
    
    if pam50_normalization:
        normalization_flag = "-normalize-PAM50 1"
    else:
        normalization_flag = ""

    # Run asymmetry computation
    assert os.system(f"sct_process_segmentation -i {sc_mask} -anat {image} -perslice 1 -qc {qc_folder} -o {output_csv} -discfile {vert_levels} {normalization_flag}") == 0, "Error running the sct_compute_asymmetry command"

    # Add the following columns
    df_asymmetry = pd.read_csv(output_csv)
    # We create the ratio columns for the anterior and posterior quadrants
    df_asymmetry["RATIO(area_quadrant_anterior_left/right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] / df_asymmetry["MEAN(area_quadrant_anterior_right)"]
    df_asymmetry["RATIO(area_quadrant_posterior_left/right)"] = df_asymmetry["MEAN(area_quadrant_posterior_left)"] / df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    # We create the difference columns for the anterior and posterior quadrants
    df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] - df_asymmetry["MEAN(area_quadrant_anterior_right)"]
    df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["MEAN(area_quadrant_posterior_left)"] - df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    # We create a normalized difference column for the anterior and posterior quadrants (difference divided by the mean of the two quadrants)
    df_asymmetry["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_anterior_left)"]
    df_asymmetry["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_posterior_left)"]
    
    # Save the updated dataframe to the same csv file
    df_asymmetry.to_csv(output_csv, index=False)

    return output_csv


def plot_asymmetry(asymmetry_csv, lesion_statistics, output_path):
    """
    This function plots the asymmetry results.
    Input:
        asymmetry_csv: Path to the csv file containing the asymmetry results
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    path_asymmetry_plot = os.path.join(output_path, "asymmetry_plot.png")

    if os.path.exists(path_asymmetry_plot):
        return path_asymmetry_plot
    
    # Load the asymmetry results
    df_asymmetry = pd.read_csv(asymmetry_csv)
    # Get subject ID from output path
    subject_id = output_path.split("/")[-1]
    # Create the plot
    create_lineplot_asymetry(df_asymmetry, subject_id, path_asymmetry_plot, lesion_statistics)

    return path_asymmetry_plot


def plot_asymmetry_with_hc(asymmetry_csv, path_hc_data, lesion_statistics, output_path):
    """
    This function plots the asymmetry results compared to a healthy control group.
    Input:
        asymmetry_csv: Path to the csv file containing the asymmetry results
        path_hc_data: Path to the healthy control data folder for asymmetry comparison
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    path_asymmetry_plot_hc = os.path.join(output_path, "asymmetry_plot_hc.png")

    if os.path.exists(path_asymmetry_plot_hc):
        return path_asymmetry_plot_hc
    
    # Load the asymmetry results
    df_asymmetry = pd.read_csv(asymmetry_csv)
    # We create a normalized difference column for the anterior and posterior quadrants (difference divided by the mean of the two quadrants)
    df_asymmetry["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_anterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_anterior_left)"]
    df_asymmetry["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_asymmetry["DIFF(area_quadrant_posterior_left-right)"] / df_asymmetry["MEAN(area_quadrant_posterior_left)"]
    df_asymmetry["DIFF(area_left-right)"] = df_asymmetry["MEAN(area_quadrant_anterior_left)"] + df_asymmetry["MEAN(area_quadrant_posterior_left)"] - df_asymmetry["MEAN(area_quadrant_anterior_right)"] - df_asymmetry["MEAN(area_quadrant_posterior_right)"]
    df_asymmetry["NORM_DIFF(area_left-right)"] = df_asymmetry["DIFF(area_left-right)"] / (df_asymmetry["MEAN(area_quadrant_anterior_left)"] + df_asymmetry["MEAN(area_quadrant_posterior_left)"])
    # Get subject ID from output path
    subject_id = output_path.split("/")[-1]
    # Get min and max slice index from the asymmetry csv to load only the relevant slices from the healthy control data
    min_slice_idx = df_asymmetry["Slice (I->S)"].min()
    max_slice_idx = df_asymmetry["Slice (I->S)"].max()

    data_tsv = os.path.join(path_hc_data, "participants.tsv")
    
    # Load healthy control data
    df_hc = load_normative_data_asymmetry(path_hc_data, data_tsv, min_slice=min_slice_idx, max_slice=max_slice_idx)
    # We create the diff columns for the healthy control group as well
    df_hc["DIFF(area_quadrant_anterior_left-right)"] = df_hc["MEAN(area_quadrant_anterior_left)"] - df_hc["MEAN(area_quadrant_anterior_right)"]
    df_hc["DIFF(area_quadrant_posterior_left-right)"] = df_hc["MEAN(area_quadrant_posterior_left)"] - df_hc["MEAN(area_quadrant_posterior_right)"]
    df_hc["DIFF(area_left-right)"] = df_hc["MEAN(area_quadrant_anterior_left)"] + df_hc["MEAN(area_quadrant_posterior_left)"] - df_hc["MEAN(area_quadrant_anterior_right)"] - df_hc["MEAN(area_quadrant_posterior_right)"]
    # We create the norm diff columns for the healthy control group as well
    df_hc["NORM_DIFF(area_quadrant_anterior_left-right)"] = df_hc["DIFF(area_quadrant_anterior_left-right)"] / df_hc["MEAN(area_quadrant_anterior_left)"]
    df_hc["NORM_DIFF(area_quadrant_posterior_left-right)"] = df_hc["DIFF(area_quadrant_posterior_left-right)"] / df_hc["MEAN(area_quadrant_posterior_left)"]
    df_hc["NORM_DIFF(area_left-right)"] = df_hc["DIFF(area_left-right)"] / (df_hc["MEAN(area_quadrant_anterior_left)"] + df_hc["MEAN(area_quadrant_posterior_left)"])

    # Create the plot
    create_lineplot_asymetry_with_hc(df_asymmetry, df_hc, subject_id, path_asymmetry_plot_hc, lesion_statistics)

    return path_asymmetry_plot_hc


def detect_laterality(image, lesion_mask, sc_mask, discs_levels, lesion_statistics, output_path, qc_folder):
    """
    This function detects the laterality of the lesions based on the sct_analyze_lesion command.
    We run the command for each lesion separately to get the laterality of each lesion.
    We do this because we want to be sure that the lesion we indexed as 1 before is the same lesion indexed as 1 by sct_analyze_lesion.
    Inspiration: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/5049

    Input:
        image: Path to the input image (NIfTI format)
        lesion_mask: Path to the lesion mask (NIfTI format)
        sc_mask: Path to the SC segmentation mask (NIfTI format)
        discs_levels: Path to the vertebral labeling (NIfTI format)
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
        qc_folder: Path to the quality control folder
    Output:
        A report containing the laterality of each lesion
    """
    # Build laterality_folder
    laterality_folder = os.path.join(output_path, "laterality_outputs")
    os.makedirs(laterality_folder, exist_ok=True)

    # Build output report path
    laterality_report_folder = os.path.join(output_path, "laterality_report")
    if os.path.exists(laterality_report_folder):
        return laterality_report_folder
    # Or we build it
    os.makedirs(laterality_report_folder, exist_ok=True)

    # Here we chose the vert levels to keep:
    disc_level_data = nib.load(discs_levels).get_fdata()
    unique_labels = np.unique(disc_level_data).tolist()
    unique_labels = [int(label) for label in unique_labels if label != 0] # Remove background label
    # We want to select the level at 3 and 7 if they are present in the unique labels, else, we select the 25% and 75% quantiles of the unique labels
    first_level = 3 if 3 in unique_labels else int(np.quantile(unique_labels, 0.25))
    second_level = 7 if 7 in unique_labels else int(np.quantile(unique_labels, 0.75))
    print(f"Unique vertebral levels found: {unique_labels}. We will keep the levels {first_level} and {second_level} for the laterality analysis.")

    # Keep only vert 3 and 7 
    disc_levels_only_2 = os.path.join(output_path, discs_levels.replace(".nii.gz", "_only_2.nii.gz"))
    assert os.system(f"sct_label_utils -i {discs_levels} -o {disc_levels_only_2} -keep {first_level},{second_level}") == 0, "Error running the sct_label_utils command to keep only vert 3 and 7"

    # Register to template
    # registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=seg,algo=bsplinesyn,slicewise=1,iter=20"
    # registration_param = "step=1,type=seg,algo=centermass:step=2,type=seg,algo=bsplinesyn,metric=CC,iter=10,smooth=1,slicewise=1"
    registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=0"
    # registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=1"
    # registration_param = "step=1,type=imseg,algo=centermassrot,rot_method=pcahog:step=2,type=seg,algo=bsplinesyn,iter=5,slicewise=1,metric=CC,smooth=1:step=3,type=im,algo=syn,iter=5,slicewise=1,metric=CC,smooth=1"
    assert os.system(f"sct_register_to_template -i {image} -s {sc_mask} -ldisc {disc_levels_only_2} -param {registration_param} -c t2 -ofolder {laterality_folder} -qc {qc_folder}") == 0, "Error running the sct_register_to_template command"
    
    # Warp atlas to the subject space
    path_template = os.path.join(laterality_folder, "warp_template2anat.nii.gz")
    assert os.system(f"sct_warp_template -d {image} -w {path_template} -ofolder {laterality_folder} -qc {qc_folder}") == 0, "Error running the sct_warp_template command"

    # We perform analysis lesion by lesion:
    ## We save one mask per lesion
    for lesion in lesion_statistics:
        ## Build the path to the lesion mask
        lesion_mask_path = os.path.join(output_path, "one_lesion_per_mask", lesion_mask.split("/")[-1].replace(".nii.gz", f"_lesion_{lesion['label']}.nii.gz"))
        # Atlas-based lesion analysis
        assert os.system(f"sct_analyze_lesion -m {lesion_mask_path} -s {sc_mask} -f {laterality_folder} -perslice 1 -ofolder {laterality_report_folder}") == 0, "Error running the sct_analyze_lesion command"

    return laterality_report_folder


def plot_laterality(laterality_report_folder, lesion_mask, lesion_statistics, output_path):
    """
    This function plots the laterality results.
    Input:
        laterality_report: Path to the laterality report generated by the sct_analyze_lesion command
        lesion_mask: Path to the lesion mask (NIfTI format)
        lesion_statistics: List of dictionaries containing lesion statistics
        output_path: Path to the output folder
    Output:
        None
    """
    # Build output plot path
    laterality_plot = os.path.join(output_path, "laterality_plot.png")

    if os.path.exists(laterality_plot):
        return laterality_plot

    # Initialize the dataframe of laterality funiculi for each lesion
    df_laterality = pd.DataFrame(columns=["Slice (I->S)", "lesion_label", "white matter", "gray matter", "dorsal columns", "lateral funiculi", "ventral funiculi", "total % (all tracts)", "vert_level"])

    # Load the laterality report
    # There is one report per lesion in the xlsx file:
    for lesion in lesion_statistics:
        lesion_label = lesion["label"]
        xlsx_path = os.path.join(laterality_report_folder, lesion_mask.split("/")[-1].replace(".nii.gz", f"_lesion_{lesion_label}_analysis.xlsx")) 
        # We load the report and extract the laterality information
        xls = pd.ExcelFile(xlsx_path)
        ## We only keep page: lesion#1_distribution
        df_lesion = pd.read_excel(xls, 'lesion#1_distribution')
        # Remove the last line corresponding to the total lesion volume
        df_lesion = df_lesion[:-1]
        # Create a Slice (I->S)	column in df_laterality equal to the index
        df_lesion["Slice (I->S)"] = df_lesion.index
        ## Add this df to the df_laterality dataframe with the lesion label as index
        df_lesion["lesion_label"] = lesion_label
        df_laterality = pd.concat([df_laterality, df_lesion[["Slice (I->S)", "vert_level", "lesion_label", "white matter", "gray matter", "dorsal columns", "lateral funiculi", "ventral funiculi", "total % (all tracts)"]]], ignore_index=True)
    
    # Rename the vert_level column to VertLevel
    df_laterality = df_laterality.rename(columns={"vert_level": "VertLevel"})

    # Plot the laterality results
    sub_ID = output_path.split("/")[-1]
    create_lineplot_laterality(df_laterality, sub_ID, laterality_plot)

    return laterality_plot


def detect_critical_lesions(input_scan, output_path, pam_50_csa_folder, path_hc_data):

    # Build the output folder
    image_name = input_scan.split("/")[-1].replace(".nii.gz", "")
    output_path = os.path.join(output_path, image_name)
    os.makedirs(output_path, exist_ok=True)
    qc_folder = os.path.join(output_path, "qc")
    os.makedirs(qc_folder, exist_ok=True)

    # Placeholder for the actual lesion detection logic
    print(f"Detecting critical lesions in scan: {input_scan}")
    # Copy img to output folder
    assert os.system(f"cp {input_scan} {output_path}") == 0, "Error copying the input scan to the output folder"
    # SC segmentation
    sc_mask = run_sc_segmentation(input_scan, output_path, qc_folder)
    # Vert labeling
    vert_levels =run_vert_labeling(input_scan, output_path, qc_folder)
    # Lesion segmentation
    lesion_mask = run_lesion_segmentation(input_scan, sc_mask, output_path, qc_folder)
    
    # For each lesion, we compute its CoM and size
    lesion_statistics = get_lesion_stats(lesion_mask, sc_mask, input_scan, vert_levels,output_path, qc_folder)

    # Now we investigate the detection of spinal cord atrophy
    norm_csa_file = compute_normalized_csa(sc_mask, vert_levels, output_path, qc_folder)

    # Now we plot the CSA compared to the PAM50
    path_csa_plot = plot_csa(norm_csa_file, pam_50_csa_folder, output_path)

    # Now we perform asymetry computation
    asymetry_csv = compute_asymmetry(input_scan, sc_mask, vert_levels, output_path, qc_folder)

    # Plot asymetry
    path_asymmetry_plot = plot_asymmetry(asymetry_csv, lesion_statistics, output_path)

    asymetry_csv_pam50 = compute_asymmetry(input_scan, sc_mask, vert_levels, output_path, qc_folder, pam50_normalization=True)
    
    # Plot asymetry with HC group
    path_asymmetry_plot_hc = plot_asymmetry_with_hc(asymetry_csv_pam50, path_hc_data, lesion_statistics, output_path)

    # Detect laterality
    laterality_report_folder = detect_laterality(input_scan, lesion_mask, sc_mask, vert_levels, lesion_statistics, output_path, qc_folder)

    # Plot laterality results
    laterality_plot = plot_laterality(laterality_report_folder, lesion_mask, lesion_statistics, output_path)


if __name__ == "__main__":
    args = parse_arguments()
    detect_critical_lesions(args.input, args.output_folder, args.pam50, args.hc_data)